version: '3.8'

networks:
  local-network:
    external: true

volumes:
  campeonato-database: {}
  data: {}

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./data:/app/data
    networks:
      - local-network
  db:
    image: postgres:15-alpine
    restart: 'no'
    tty: true
    ports:
      - ${DB_EXTERNAL_PORT:-15433}:5432
    volumes:
      - campeonato-database:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - local-network


