version: '3.8'

networks:
  local-network:
    external: true

volumes:
  local-database: {}

services:
  db:
    image: postgres:15-alpine
    restart: 'no'
    tty: true
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    volumes:
      - local-database:/var/lib/postgresql/data
      - ./internal/infra/db/migrations:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - local-network
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    networks:
      - local-network

