basePath: /
definitions:
  dto.CreateFootballFanDTO:
    properties:
      email:
        type: string
      name:
        type: string
      team:
        type: string
    type: object
  entity.Competition:
    properties:
      id:
        type: integer
      name:
        type: string
      season:
        type: integer
    type: object
  entity.FootballFan:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      team:
        type: string
      updated_at:
        type: string
    type: object
  entity.Match:
    properties:
      awayTeam:
        type: string
      homeTeam:
        type: string
      score:
        type: string
    type: object
  handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handler.FootballFanResponse:
    properties:
      fan:
        $ref: '#/definitions/entity.FootballFan'
      mensagem:
        type: string
    type: object
  handler.LoginRequest:
    properties:
      email:
        example: user@test.com
        type: string
      password:
        example: "123456"
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Christopher Fernandes
  description: Competition API with auhtentication
  termsOfService: http://swagger.io/terms/
  title: API Rest Competition
  version: "1.0"
paths:
  /api/v1/competitions:
    get:
      consumes:
      - application/json
      description: Retorna uma lista de competições disponíveis
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Competition'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Obtém todas as competições
      tags:
      - Competitions
  /api/v1/competitions/{id}/matches:
    get:
      consumes:
      - application/json
      description: Retorna as partidas de uma competição pelo ID, podendo filtrar
        por rodada e equipe.
      parameters:
      - description: ID da Competição
        in: path
        name: id
        required: true
        type: integer
      - description: Número da Rodada
        in: query
        name: rodada
        type: integer
      - description: Nome da Equipe
        in: query
        name: equipe
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Match'
            type: array
        "400":
          description: Erro nos parâmetros da requisição
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Retorna partidas de uma competição
      tags:
      - Competitions
  /api/v1/football-fan:
    post:
      consumes:
      - application/json
      description: Cria um novo torcedor de futebol com os dados fornecidos e retorna
        o torcedor criado
      parameters:
      - description: Dados do Torcerdor de Futebol
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.CreateFootballFanDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Sucesso
          schema:
            $ref: '#/definitions/handler.FootballFanResponse'
        "400":
          description: Requisição inválida
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Cria um novo torcedor de futebol
      tags:
      - FootballFan
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Autentica o usuário e retorna um token JWT para acesso às rotas
        protegidas.
      parameters:
      - description: Dados de login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Token gerado com sucesso
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Usuário ou senha incorretos
          schema:
            additionalProperties: true
            type: object
      summary: Realiza o login do usuário
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
