version: "2"
sql:
- schema: "/migrations"
  queries: "/queries"
  engine: "postgresql"
  gen:
    go:
      package: "sqlc"
      out: "../repository/sqlc"
      overrides:
        - column: "users.updated_at"
          go_type: "time.Time"
        - column: "football_fans.updated_at"
          go_type: "time.Time"
